services:
  fastapi-service:
    build: ./fastapi-service
    ports:
      - "50051:50051"
    command: python app/grpc_server.py

  nestjs-gateway:
    build: ./cc-gateway
    ports:
      - "3000:3000"
    depends_on:
      - fastapi-service
    environment:
      - GRPC_SERVER_URL=fastapi-service:50051
